### ISSUE TITLE
Using Labkit with matlab MIJ

### ISSUE THREAD

**Issue by GrimmSnark** [juglab/labkit-ui#104]
Hello,

I am trying to incorporate the labkit pixel classification into my existing matlab MIJ pipeline. At this stage of the code the image set I am trying to segement is open in FIJI within matlab. When I try and run the command 

```
segFilePath = 'C:\Data\mouse\calcium\FN1\20230427\waveClass.classifier';
MIJ.run('Segment Image With Labkit', ['segmenter_file=' segFilePath ' use_gpu=false']);
```

I get the following error code

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at ij.IJ.run(IJ.java:319)
	at MIJ.run(MIJ.java:1171)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 6 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:868)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at sc.fiji.labkit.pixel_classification.pixel_feature.settings.FeatureSettings.fromJson(FeatureSettings.java:79)
	at sc.fiji.labkit.pixel_classification.classification.Segmenter.fromJson(Segmenter.java:240)
	at sc.fiji.labkit.ui.segmentation.weka.TrainableSegmentationSegmenter.openModel(TrainableSegmentationSegmenter.java:346)
	at sc.fiji.labkit.ui.segmentation.SegmentationTool.openModel(SegmentationTool.java:85)
	at sc.fiji.labkit.ui.plugin.SegmentImageWithLabkitPlugin.run(SegmentImageWithLabkitPlugin.java:81)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:139)
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:70)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165)
	... 19 more
```

Any help or advice would be greatly appreciated.

**Comment by maarzt** [comment]
@GrimmSnark Thank you for reporting the issue.
So far I have no experience running Labkit in MATLAB.

But the error message tells me that the exception occurred while reading the classifier file. ('C:\Data\mouse\calcium\FN1\20230427\waveClass.classifier' in your case.) Do you get the same error when opening the file from Labkit in Fiji? Are you sure the file is correct and has not been corrupted?

**Comment by maarzt** [comment]
Feel free to reopen the issue if the problem persists.
