### ISSUE TITLE
ERror when starting labkit

### ISSUE THREAD

**Issue by haesleinhuepf** [juglab/labkit-ui#64]
Hi @maarzt ,

I just tested Labkit in Fiji (not the GPU-preview, the official version). When starting it from the menu, Labkit doesn't open up and shows this error instead:
```
[ERROR] Module threw error
java.lang.NoSuchMethodError: bdv.viewer.ViewerPanel.getDisplay()Lnet/imglib2/ui/InteractiveDisplayCanvasComponent;
	at net.imglib2.labkit.brush.LabelBrushController.<init>(LabelBrushController.java:64)
	at net.imglib2.labkit.BasicLabelingComponent.initBrushLayer(BasicLabelingComponent.java:97)
	at net.imglib2.labkit.BasicLabelingComponent.<init>(BasicLabelingComponent.java:53)
	at net.imglib2.labkit.SegmentationComponent.<init>(SegmentationComponent.java:50)
	at net.imglib2.labkit.LabkitFrame.initSegmentationComponent(LabkitFrame.java:62)
	at net.imglib2.labkit.LabkitFrame.<init>(LabkitFrame.java:52)
	at net.imglib2.labkit.LabkitFrame.show(LabkitFrame.java:46)
	at net.imglib2.labkit.LabkitFrame.showForImage(LabkitFrame.java:40)
	at net.imglib2.labkit.plugin.LabkitPlugin.run(LabkitPlugin.java:27)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

Might there any other update site needed for running labkit?

Thanks for any hint!

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Addendum: After removing the BDV-playground update site maintained by @NicoKiaru, it works.

Thanks for listening :-)

**Comment by haesleinhuepf** [comment]
Addendum: I just tried with the Labkit-Preview and it shows the error message above.

**Comment by maarzt** [comment]
Looks like there will be an update to BigDataViewer 10 next week. That should fix these kind of problems.
