### ISSUE TITLE
ClassCastException arising from cast to DefaultLinearAxis

### ISSUE THREAD

**Issue by gselzer** [juglab/labkit-ui#99]
I was trying to see if I could boot up Labkit from napari-imagej, but it doesn't work because I tried to call `Open Current Image With Labkit` on an image that has `EnumeratedAxis`. This causes a `ClassCastException` [here](https://github.com/juglab/labkit-ui/blob/c48a8653f1eeaaf9b42aa1049fff3d7e33578884/src/main/java/sc/fiji/labkit/ui/InitialLabeling.java#L159).

Here's the stack trace:
```
 java.lang.ClassCastException: net.imagej.axis.EnumeratedAxis cannot be cast to net.imagej.axis.DefaultLinearAxis
	at sc.fiji.labkit.ui.InitialLabeling.lambda$scaledAxes$3(InitialLabeling.java:159)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at sc.fiji.labkit.ui.InitialLabeling.scaledAxes(InitialLabeling.java:160)
	at sc.fiji.labkit.ui.InitialLabeling.defaultLabeling(InitialLabeling.java:90)
	at sc.fiji.labkit.ui.InitialLabeling.initLabeling(InitialLabeling.java:79)
	at sc.fiji.labkit.ui.InitialLabeling.initialLabeling(InitialLabeling.java:66)
	at sc.fiji.labkit.ui.LabkitFrame.showForImage(LabkitFrame.java:90)
	at sc.fiji.labkit.ui.plugin.LabkitPlugin.run(LabkitPlugin.java:56)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)

```
Can we include behavior for other `Axis` types, like `EnumeratedAxis`? I'm not sure what the behavior would look like - do we need to estimate the scale of the `EnumeratedAxis` somehow? Or do we even need to scale an `Axis` if it isn't linear?

**Comment by ctrueden** [comment]
@maarzt At minimum I would suggestion not hardcoding `DefaultLinearAxis` in favor of the `LinearAxis` interface. But you could support any `CalibratedAxis` by calling `calibratedValue(1) - calibratedValue(0)` to approximate a scale, if that's a piece of metadata you always need.

**Comment by maarzt** [comment]
@gselzer I'm happy to fix the Labkit source code, such that it will work for this use case. I will prepare a PR and then ping you again.

Any idea why EnumerateAxis is used? Is it used to represent the time axis?

(Side note: Correct calibration information, is helpful for Labkit to correctly calculate rotation invariant features for anisotropic 3d images during pixel classification. But I think the problematic code here, just processes some image meta data that might not even be used in the end. So let's fix or remove it.)

**Comment by maarzt** [comment]
This commit c4e5d6ac2653b49d9bebddfac690403e893438c6 (on master) should fix the problem. I didn't create a PR, it's a very simple fix.

Please tell me if it works for you, or if you need something else, release etc. I'm also happy to learn how to start Labkit form napari.

**Comment by gselzer** [comment]
> Any idea why EnumerateAxis is used? Is it used to represent the time axis?

If I understand correctly, the reason we have `EnumerateAxis` is because we are creating an `Img` by wrapping a backing xarray object, which does not make any guarantees about linearity, so we cannot use a `LinearAxis` implementation. But I was not the one doing this work.

> This commit https://github.com/juglab/labkit-ui/commit/c4e5d6ac2653b49d9bebddfac690403e893438c6 (on master) should fix the problem. I didn't create a PR, it's a very simple fix.

Yup, looks like it works! Thanks @maarzt! 

![image](https://user-images.githubusercontent.com/29754838/215516302-f48a046a-a74a-4ba1-904b-f0c1afb5ccdc.png)

> Please tell me if it works for you, or if you need something else, release etc. I'm also happy to learn how to start Labkit form napari.

All you have to do to start Labkit from napari is run napari-imagej (installation instructions [here](https://github.com/imagej/napari-imagej/blob/main/README.md#installation)), and if the backing ImageJ2 has Labkit then Labkit plugins will automatically be available from the search bar:
